#!/bin/bash

sudo rtcwake -m no -l -t "$(date -d 'tomorrow 00:00' '+%s')"
sudo rtcwake -m no -l -t "$(date -d 'tomorrow 01:00' '+%s')"
sudo rtcwake -m no -l -t "$(date -d 'tomorrow 02:00' '+%s')"
sudo rtcwake -m no -l -t "$(date -d 'tomorrow 03:00' '+%s')"
sudo rtcwake -m no -l -t "$(date -d 'tomorrow 04:00' '+%s')"
sudo rtcwake -m no -l -t "$(date -d 'tomorrow 05:00' '+%s')"
sudo rtcwake -m no -l -t "$(date -d 'tomorrow 06:00' '+%s')"
sudo rtcwake -m no -l -t "$(date -d 'tomorrow 07:00' '+%s')"
sudo rtcwake -m no -l -t "$(date -d 'tomorrow 08:00' '+%s')"
sudo rtcwake -m no -l -t "$(date -d 'tomorrow 09:00' '+%s')"
sudo rtcwake -m no -l -t "$(date -d 'tomorrow 10:00' '+%s')"
sudo rtcwake -m no -l -t "$(date -d 'tomorrow 11:00' '+%s')"
sudo rtcwake -m no -l -t "$(date -d 'tomorrow 12:00' '+%s')"
sudo rtcwake -m no -l -t "$(date -d 'tomorrow 13:00' '+%s')"
sudo rtcwake -m no -l -t "$(date -d 'tomorrow 14:00' '+%s')"
sudo rtcwake -m no -l -t "$(date -d 'tomorrow 15:00' '+%s')"
sudo rtcwake -m no -l -t "$(date -d 'tomorrow 16:00' '+%s')"
sudo rtcwake -m no -l -t "$(date -d 'tomorrow 17:00' '+%s')"
sudo rtcwake -m no -l -t "$(date -d 'tomorrow 18:00' '+%s')"
sudo rtcwake -m no -l -t "$(date -d 'tomorrow 19:00' '+%s')"
sudo rtcwake -m no -l -t "$(date -d 'tomorrow 20:00' '+%s')"
sudo rtcwake -m no -l -t "$(date -d 'tomorrow 21:00' '+%s')"
sudo rtcwake -m no -l -t "$(date -d 'tomorrow 22:00' '+%s')"
sudo rtcwake -m no -l -t "$(date -d 'tomorrow 23:00' '+%s')"
